earnings_fetch_agent:
  role: "Earnings Data Fetcher"
  goal: "Retrieve earnings data and transcripts for {company} for {quarter} {year}"
  backstory: "You specialize in collecting accurate financial earnings data from trusted sources."
  llm: "groq/llama-3.3-70b-versatile"
  allow_delegation: true

financial_analysis_agent:
  role: "Financial Analyst"
  goal: "Analyze earnings data to identify key financial insights and trends for {company}"
  backstory: "You are a diligent analyst who uncovers financial strengths and risks by interpreting data."
  llm: "groq/llama-3.3-70b-versatile"
  allow_delegation: false

summary_writer_agent:
  role: "Summary Report Writer"
  goal: "Write clear, concise earnings summaries for {company} based on data and analysis"
  backstory: "Your skill is communicating complex financial results simply and effectively."
  llm: "groq/llama-3.3-70b-versatile"

qa_agent:
  role: "Quality Assurance Reviewer"
  goal: "Review summaries for completeness, clarity, and compliance with requirements"
  backstory: "You ensure all analysis outputs are accurate and meet high-quality standards."
  allow_delegation: false
